-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid,
  owner_id uuid,
  veterinarian_id uuid,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 30,
  reason character varying NOT NULL,
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no-show'::character varying]::text[])),
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT appointments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.owners(id),
  CONSTRAINT appointments_veterinarian_id_fkey FOREIGN KEY (veterinarian_id) REFERENCES public.users(id)
);
CREATE TABLE public.client_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  client_name character varying NOT NULL,
  client_email character varying NOT NULL,
  client_phone character varying NOT NULL,
  delivery_address text NOT NULL,
  subtotal numeric NOT NULL,
  tax_amount numeric NOT NULL,
  total_amount numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'preparing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  payment_method character varying NOT NULL,
  estimated_delivery_date date,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT client_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinic_configuration (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_name character varying DEFAULT 'VetClinic Pro'::character varying,
  address text,
  phone character varying,
  email character varying,
  opening_hours time without time zone DEFAULT '08:00:00'::time without time zone,
  closing_hours time without time zone DEFAULT '18:00:00'::time without time zone,
  default_appointment_duration integer DEFAULT 30,
  appointment_reminders boolean DEFAULT true,
  reminder_hours_before integer DEFAULT 24,
  allow_online_appointments boolean DEFAULT true,
  default_tax_rate numeric DEFAULT 16.00,
  currency character varying DEFAULT 'EUR'::character varying,
  invoice_prefix character varying DEFAULT 'FAC-'::character varying,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  low_stock_alerts boolean DEFAULT true,
  session_timeout_hours integer DEFAULT 8,
  require_password_change boolean DEFAULT false,
  max_login_attempts integer DEFAULT 3,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  emergency_phone text,
  tax_id text,
  CONSTRAINT clinic_configuration_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  product_id uuid,
  description character varying NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid,
  pet_id uuid,
  appointment_id uuid,
  invoice_number character varying NOT NULL UNIQUE,
  invoice_date date NOT NULL,
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'overdue'::character varying, 'cancelled'::character varying]::text[])),
  payment_method character varying,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.owners(id),
  CONSTRAINT invoices_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT invoices_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.medical_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid,
  veterinarian_id uuid,
  visit_date date NOT NULL,
  reason_for_visit text NOT NULL,
  symptoms text,
  diagnosis text,
  treatment text,
  medications text,
  follow_up_notes text,
  weight numeric,
  temperature numeric,
  next_appointment date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT medical_records_veterinarian_id_fkey FOREIGN KEY (veterinarian_id) REFERENCES public.users(id),
  CONSTRAINT medical_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.client_orders(id)
);
CREATE TABLE public.owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying,
  phone character varying NOT NULL,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT owners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid,
  name character varying NOT NULL,
  species character varying NOT NULL,
  breed character varying,
  color character varying,
  gender character varying CHECK (gender::text = ANY (ARRAY['Male'::character varying, 'Female'::character varying, 'Macho'::character varying, 'Hembra'::character varying]::text[])),
  date_of_birth date,
  weight numeric,
  microchip_number character varying,
  active boolean DEFAULT true,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.owners(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  category character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  cost numeric,
  stock_quantity integer NOT NULL DEFAULT 0,
  low_stock_threshold integer DEFAULT 10,
  supplier character varying,
  barcode character varying,
  expiration_date date,
  location character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  full_name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'receptionist'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'veterinarian'::character varying, 'receptionist'::character varying]::text[])),
  phone character varying,
  specialty character varying,
  license_number character varying,
  hire_date date,
  salary numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

alter table products add column image_url text;